[project]
name = "dev-tools"

[atom]
path = "dev"

[fetch.pkgs]
name = "nixpkgs"
import = true
args = [{}]

[compose.features]
atom = ["std"]
std  = ["pkg_lib"]

[backend.nix]
# default when `eka` cli is ready
# fetcher = "native"
fetcher = "npins"

[fetcher.npins]
root = "npins"
