[atom]
name = "dev"

[fetch.pkgs]
name = "nixpkgs"
import = true
args = [{}]

[core]
features = ["std"]
[std]
features = ["lib"]

[backend.nix]
# default when `eka` cli is ready
# fetcher = "native"
fetcher = "npins"

[fetcher.npins]
root = "npins"
